version: '3.8'

services:
  backend:
    image: jin03/proyecto_ea-backend:latest
    container_name: backend-prod
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URL=${MONGO_URL} # Se lee del .env del servidor
      - JWT_SECRET=${JWT_SECRET}
      # Añade aquí otras variables críticas
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
